name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 獲取完整的 git 歷史記錄，這對於某些操作可能是必要的

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install
          npm install -g repomix

      - name: Run AI Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
        run: |
          # 保存當前目錄
          BASE_DIR=$(pwd)
          cd ai-pr-reviewer
          # 將目標儲存庫路徑傳給 repomix
          pipenv run python -m src.main --repo ${{ github.repository }} --pr ${{ github.event.pull_request.number }} --include "$BASE_DIR/**/*"